### ISSUE TITLE
Remove dependency on django-crispy-forms

### ISSUE THREAD

**Issue by pydanny** [jazzband/django-admin2#343]
As much as I like the library, I'm unhappy with it's presence. This is because it removes from us the easy ability to more readily create custom features like the `readonly_fields` attribute without even more hacking on form objects. In fact, all we use it for is simple rendering of the form in templates, which isn't enough.

Tasks:

* Remove from dependency list
* Remove from INSTALLED_APPS.
* Create an includes/form.html template that renders forms.

**Comment by auvipy** [comment]
fixed
