### ISSUE TITLE
Excluding Fields from User Model

### ISSUE THREAD

**Issue by nickbewley** [jazzband/django-admin2#413]
How can we exclude fields from the User Model in the Admin? 

```
from MyApp.models import *
from django.contrib.auth.models import User
import djadmin2

class MyUserAdmin(djadmin2.ModelAdmin2):
    exclude = ('last_login', 'password', 'user_permissions')    

djadmin2.default.deregister(User)
djadmin2.default.register(User, MyUserAdmin)
```

^This would work with the traditional django admin, but doesn't work here. Any ideas? Thanks!

**Comment by andrewsmedina** [comment]
The `exclude` (#270) is not implemented yet. But you can do it customizing the create / update form: http://django-admin2.readthedocs.org/en/latest/ref/forms.html#step-2-web-integration
