### ISSUE TITLE
0.7.0 release

### ISSUE THREAD

**Issue by andrewsmedina** [jazzband/django-admin2#451]
I should make a new release with new Django versions support. To do it is necessary

- change `__version__`
- change history.md with the release notes
- remake the 0.7.0 tag

**Comment by auvipy** [comment]
Should we add 0.7.0 milestones tag to all the issues / PR's fixed from the previous release?

**Comment by andrewsmedina** [comment]
I don't know if has issues for the things done between 0.6.1 and 0.7.0. Create the missing issues isn't mandatory

**Comment by auvipy** [comment]
ok lets go for the release :+1:

**Comment by auvipy** [comment]
a10ff4637b56ad05583f4b0e25a0f00c11df1cb5 and 047ed08a8a01678a1ca133f5c5c66397a86ce2dc should be enough?
