### ISSUE TITLE
New Transifex maintainer wanted

### ISSUE THREAD

**Issue by dbrgn** [jazzband/django-admin2#459]
I'm still the maintainer for the project on Transifex, but don't have the time to maintain it. (I simply set it up during a hackathon at EuroPython some years ago.)

There's at least one language review pending (Russian).

Is there someone that could take over maintenance?

**Comment by auvipy** [comment]
I am here :)

**Comment by dbrgn** [comment]
I invited a user named "auvipy" on Transifex. If you can confirm here, I can make you the manager of the project.

**Comment by auvipy** [comment]
im auvipy :+1:

**Comment by dbrgn** [comment]
@auvipy you're now project maintainer :)

**Comment by auvipy** [comment]
thank you :)
