### ISSUE TITLE
Plans for future release Django 2.x?

### ISSUE THREAD

**Issue by koddr** [jazzband/django-admin2#461]
Hello.

My question: do you have plans for supporting and improved your django-admin2 for working in Django 2.0? I asked that because last version of package released on Jan 2017 and nothing to update/improve in code base, only dependencies.

I worry about project is dead.. but don't believe to!

Btw, thanks for awesome package.

**Comment by andrewsmedina** [comment]
We should support Django 2.x. But, currently nobody is working on it. If someone want to contribute is a good place to start.

**Comment by auvipy** [comment]
try master branch and report please. I have changed some codes to fix dj 1.11 and 2.0 conflicts
