### ISSUE TITLE
No update since roughly one year. State of the project?1

### ISSUE THREAD

**Issue by guettli** [jazzband/django-admin2#470]
Please tell us about the state of this project. Is it still alive?

Which alternative do you recommend?

**Comment by fabiocaccamo** [comment]
@guettli you could try: https://github.com/fabiocaccamo/django-admin-interface

**Comment by guettli** [comment]
@fabiocaccamo why not update the README of this repo?

**Comment by fabiocaccamo** [comment]
I'm the author of `django-admin-interface`, I'm don't mantain this repo.

**Comment by galuszkak** [comment]
Hi @guettli ,

I've updated all dependencies to the latest version so it can work with Django 2.2/3.0/3.1. Track this work in #473
