### ISSUE TITLE
ERROR: django-admin2 0.7.1 has requirement django-filter==1.0.0, but you'll have django-filter 2.3.0 which is incompatible.

### ISSUE THREAD

**Issue by nab5m** [jazzband/django-admin2#472]
can you update django-filter dependency?

**Comment by galuszkak** [comment]
@nab5m this works is inside #473

**Comment by nab5m** [comment]
Thank you :)

**Comment by auvipy** [comment]
i think should be fixed in master

**Comment by galuszkak** [comment]
@auvipy this isn't on `master`. 

This commit is only available in `develop` branch.

**Comment by auvipy** [comment]
ops
